In [1]:
import pandas as pd
import numpy as np
import random

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
random.seed(42)

products = [
    ("Laptop", "Electronics", 65000),
    ("Smartphone", "Electronics", 28000),
    ("Headphones", "Electronics", 2500),
    ("Office Chair", "Furniture", 9000),
    ("Desk", "Furniture", 12000),
    ("Backpack", "Accessories", 1800),
    ("Running Shoes", "Footwear", 3500),
    ("T-Shirt", "Clothing", 900),
    ("Jeans", "Clothing", 1800),
    ("Coffee Maker", "Home Appliances", 5500)
]

segments = ["Consumer", "Corporate", "Small Business"]
regions = ["North", "South", "East", "West"]

rows = []

for i in range(1, 201):

    product, category, price = random.choice(products)

    quantity = random.randint(1, 5)
    discount = random.choice([0, 5, 10, 15])

    sales = price * quantity * (1 - discount / 100)

    profit = sales * random.uniform(0.10, 0.30)

    rows.append([
        f"ORD{i:04d}",
        pd.Timestamp("2025-01-01") + pd.Timedelta(days=random.randint(0, 364)),
        f"CUST{random.randint(1001, 1060)}",
        random.choice(segments),
        product,
        category,
        random.choice(regions),
        quantity,
        discount,
        round(sales, 2),
        round(profit, 2)
    ])

df = pd.DataFrame(rows, columns=[
    "Order_ID",
    "Order_Date",
    "Customer_ID",
    "Customer_Segment",
    "Product",
    "Category",
    "Region",
    "Quantity",
    "Discount_Percent",
    "Sales",
    "Profit"
])

print("E-commerce dataset created successfully!")

display(df.head())

E-commerce dataset created successfully!

,Order_ID,Order_Date,Customer_ID,Customer_Segment,Product,Category,Region,Quantity,Discount_Percent,Sales,Profit
0,ORD0001,2025-03-13,CUST1048,Consumer,Smartphone,Electronics,North,1,10,25200.0,3754.25
1,ORD0002,2025-04-22,CUST1015,Small Business,Coffee Maker,Home Appliances,North,4,0,22000.0,2331.11
2,ORD0003,2025-10-29,CUST1018,Consumer,Jeans,Clothing,South,2,15,3060.0,440.91
3,ORD0004,2025-06-22,CUST1007,Consumer,Running Shoes,Footwear,West,3,10,9450.0,1238.86
4,ORD0005,2025-01-23,CUST1047,Corporate,Smartphone,Electronics,North,3,10,75600.0,16688.34

In [3]:
df["Year"] = df["Order_Date"].dt.year

df["Month"] = df["Order_Date"].dt.month

df["Month_Name"] = df["Order_Date"].dt.strftime("%B")

df["Year_Month"] = df["Order_Date"].dt.strftime("%Y-%m")

df["Profit_Margin"] = df["Profit"] / df["Sales"]

print("Feature engineering completed!")

Feature engineering completed!

In [4]:
print("Dataset information:")
df.info()

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          200 non-null    str
 1   Order_Date        200 non-null    datetime64[us]
 2   Customer_ID       200 non-null    str
 3   Customer_Segment  200 non-null    str
 4   Product           200 non-null    str
 5   Category          200 non-null    str
 6   Region            200 non-null    str
 7   Quantity          200 non-null    int64
 8   Discount_Percent  200 non-null    int64
 9   Sales             200 non-null    float64
 10  Profit            200 non-null    float64
 11  Year              200 non-null    int32
 12  Month             200 non-null    int32
 13  Month_Name        200 non-null    str
 14  Year_Month        200 non-null    str
 15  Profit_Margin     200 non-null    float64
dtypes: datetime64[us](1), float64(3), int32(2), int64(2), str(8)
memory usage: 35.6 KB

In [5]:
print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

display(df.head())

Dataset shape: (200, 16)

Column names:
['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Segment', 'Product', 'Category', 'Region', 'Quantity', 'Discount_Percent', 'Sales', 'Profit', 'Year', 'Month', 'Month_Name', 'Year_Month', 'Profit_Margin']

,Order_ID,Order_Date,Customer_ID,Customer_Segment,Product,Category,Region,Quantity,Discount_Percent,Sales,Profit,Year,Month,Month_Name,Year_Month,Profit_Margin
0,ORD0001,2025-03-13,CUST1048,Consumer,Smartphone,Electronics,North,1,10,25200.0,3754.25,2025,3,March,2025-03,0.148978
1,ORD0002,2025-04-22,CUST1015,Small Business,Coffee Maker,Home Appliances,North,4,0,22000.0,2331.11,2025,4,April,2025-04,0.105960
2,ORD0003,2025-10-29,CUST1018,Consumer,Jeans,Clothing,South,2,15,3060.0,440.91,2025,10,October,2025-10,0.144088
3,ORD0004,2025-06-22,CUST1007,Consumer,Running Shoes,Footwear,West,3,10,9450.0,1238.86,2025,6,June,2025-06,0.131096
4,ORD0005,2025-01-23,CUST1047,Corporate,Smartphone,Electronics,North,3,10,75600.0,16688.34,2025,1,January,2025-01,0.220745

In [6]:
print("Missing values:")
display(df.isnull().sum())

Missing values:

Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Segment    0
Product             0
Category            0
Region              0
Quantity            0
Discount_Percent    0
Sales               0
Profit              0
Year                0
Month               0
Month_Name          0
Year_Month          0
Profit_Margin       0
dtype: int64

In [7]:
monthly_sales = df.groupby("Year_Month")["Sales"].sum()

print("Monthly Sales Trend:")
display(monthly_sales)

Monthly Sales Trend:

Year_Month
2025-01    578180.0
2025-02    965095.0
2025-03    615815.0
2025-04    391650.0
2025-05    399495.0
2025-06    401385.0
2025-07    335130.0
2025-08    522095.0
2025-09    300450.0
2025-10    349445.0
2025-11    317010.0
2025-12    414160.0
Name: Sales, dtype: float64

In [8]:
segment_sales = df.groupby("Customer_Segment")["Sales"].sum()

print("Sales by Customer Segment:")
display(segment_sales.sort_values(ascending=False))

Sales by Customer Segment:

Customer_Segment
Consumer          2393385.0
Small Business    1673075.0
Corporate         1523450.0
Name: Sales, dtype: float64

In [9]:
category_sales = df.groupby("Category")["Sales"].sum()

print("Sales by Category:")
display(category_sales.sort_values(ascending=False))

Sales by Category:

Category
Electronics        3524700.0
Furniture          1219650.0
Home Appliances     347325.0
Footwear            242725.0
Clothing            181530.0
Accessories          73980.0
Name: Sales, dtype: float64

In [10]:
region_sales = df.groupby("Region")["Sales"].sum()

print("Sales by Region:")
display(region_sales.sort_values(ascending=False))

Sales by Region:

Region
North    1697210.0
South    1635375.0
East     1468475.0
West      788850.0
Name: Sales, dtype: float64

In [11]:
top_products = (
    df.groupby("Product")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print("Top 10 Products:")
display(top_products)

Top 10 Products:

Product
Laptop           2275000.0
Smartphone       1117200.0
Desk              790800.0
Office Chair      428850.0
Coffee Maker      347325.0
Running Shoes     242725.0
Headphones        132500.0
Jeans             124830.0
Backpack           73980.0
T-Shirt            56700.0
Name: Sales, dtype: float64

In [12]:
top_customers = (
    df.groupby("Customer_ID")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print("Top 10 Customers:")
display(top_customers)

Top 10 Customers:

Customer_ID
CUST1039    378250.0
CUST1016    371700.0
CUST1026    309775.0
CUST1005    274550.0
CUST1055    249875.0
CUST1047    241350.0
CUST1043    239110.0
CUST1044    235930.0
CUST1040    226425.0
CUST1021    198150.0
Name: Sales, dtype: float64

In [13]:
total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_orders = df["Order_ID"].nunique()
total_quantity = df["Quantity"].sum()
average_order_value = total_sales / total_orders

print("----- BUSINESS SUMMARY -----")
print("Total Sales:", round(total_sales, 2))
print("Total Profit:", round(total_profit, 2))
print("Total Orders:", total_orders)
print("Total Quantity Sold:", total_quantity)
print("Average Order Value:", round(average_order_value, 2))

----- BUSINESS SUMMARY -----
Total Sales: 5589910.0
Total Profit: 1105860.15
Total Orders: 200
Total Quantity Sold: 594
Average Order Value: 27949.55

In [14]:
excel_file = "InternCircle_Task3_Ecommerce_Sales_Analysis.xlsx"

with pd.ExcelWriter(excel_file, engine="openpyxl") as writer:

    df.to_excel(
        writer,
        sheet_name="Sales_Data",
        index=False
    )

    monthly_sales.to_excel(
        writer,
        sheet_name="Monthly_Trend"
    )

    segment_sales.to_excel(
        writer,
        sheet_name="Customer_Segments"
    )

    category_sales.to_excel(
        writer,
        sheet_name="Categories"
    )

    region_sales.to_excel(
        writer,
        sheet_name="Regions"
    )

    top_products.to_excel(
        writer,
        sheet_name="Top_Products"
    )

    top_customers.to_excel(
        writer,
        sheet_name="Top_Customers"
    )

print("Excel file created successfully!")

Excel file created successfully!

In [15]:
import os

print(os.path.abspath("InternCircle_Task3_Ecommerce_Sales_Analysis.xlsx"))

C:\Users\krist\InternCircle_Task3_Ecommerce_Sales_Analysis.xlsx

In [16]:
import os

print(os.listdir())

['.anaconda', '.android', '.conda', '.continuum', '.copilot', '.emulator_console_auth_token', '.gemini', '.gitconfig', '.gradle', '.ipynb_checkpoints', '.ipython', '.jupyter', '.vscode', '.vscode-shared', 'anaconda3', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'data_visualization.ipynb', 'Documents', 'Downloads', 'Favorites', 'Flutter1', 'intellij-chatgpt', 'InternCircle_Task3_Ecommerce_Sales_Analysis.xlsx', 'JAVA', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{d5ee5dfe-8dc7-11f0-b65f-502e9101430b}.TM.blf', 'NTUSER.DAT{d5ee5dfe-8dc7-11f0-b65f-502e9101430b}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{d5ee5dfe-8dc7-11f0-b65f-502e9101430b}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'PrintHood', 'Python', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'So Lab', 'Start Menu', 'Templates', 'titanic_eda.ipynb', 'Untitled.ipynb', 'Videos']